[package]
name = "revive"
version = "0.1.0"
edition = "2021"
authors = ["Zahash <zahash.z@gmail.com>"]
description = "ui framework built on top of reactivate"
license = "MIT"
repository = "https://github.com/zahash/revive"

[dependencies]
reactivate = { version = "*" }
